/**
 * Shared export utility. Every tool that emits CSS variables, Tailwind config
 * or DTCG JSON uses these functions — no duplicated formatting logic.
 */

import type { TokenSchema, ColorPrimitive, ZIndexToken, BreakpointToken, FocusRingConfig } from './token-schema'

// ── CSS custom properties ──────────────────────────────────────────────────

export interface CssVarEntry {
  name: string
  value: string
  comment?: string
}

export function cssVarsBlock(entries: CssVarEntry[], selector = ':root'): string {
  const lines = entries.map((entry) => {
    const comment = entry.comment ? ` /* ${entry.comment} */` : ''
    return `  ${entry.name}: ${entry.value};${comment}`
  })

  return `${selector} {\n${lines.join('\n')}\n}`
}

// ── Per-category CSS exports ───────────────────────────────────────────────

export function colorPrimitivesToCss(
  primitives: Record<string, ColorPrimitive>,
  prefix = '--color',
): string {
  const entries: CssVarEntry[] = Object.entries(primitives).map(([key, token]) => ({
    name: `${prefix}-${key}`,
    value: token.$value,
  }))

  return cssVarsBlock(entries)
}

export function zIndexTokensToCss(tokens: Record<string, ZIndexToken>): string {
  const sorted = Object.entries(tokens).sort(([, a], [, b]) => a.$value - b.$value)
  const entries: CssVarEntry[] = sorted.map(([key, token]) => ({
    name: `--z-${key}`,
    value: String(token.$value),
    comment: token.label,
  }))

  return cssVarsBlock(entries)
}

export function breakpointsToCss(tokens: Record<string, BreakpointToken>): string {
  const sorted = Object.entries(tokens).sort(([, a], [, b]) => a.$value - b.$value)
  const entries: CssVarEntry[] = sorted.map(([key, token]) => ({
    name: `--breakpoint-${key}`,
    value: `${token.$value}${token.unit}`,
  }))

  return cssVarsBlock(entries)
}

export function focusRingToCss(config: FocusRingConfig): string {
  const rules = [
    '/* Focus ring — generated by Vantra Tools */',
    ':focus-visible {',
    `  outline: ${config.width}px solid ${config.color};`,
    `  outline-offset: ${config.offset}px;`,
  ]

  if (config.style === 'double' && config.haloColor) {
    rules.push(`  box-shadow: 0 0 0 ${config.offset + config.width + 2}px ${config.haloColor};`)
  }

  rules.push('}')

  return rules.join('\n')
}

export function darkModeToCss(
  lightPrimitives: Record<string, ColorPrimitive>,
  darkMapping: Record<string, string>,
  prefix = '--color',
): string {
  const entries: CssVarEntry[] = Object.entries(darkMapping).map(([key, darkValue]) => ({
    name: `${prefix}-${key}`,
    value: darkValue,
    comment: `light: ${lightPrimitives[key]?.$value ?? 'unknown'}`,
  }))

  return cssVarsBlock(entries, '@media (prefers-color-scheme: dark) {\n  :root')
    .replace(/\n\}$/, '\n  }\n}')
}

// ── Tailwind config exports ────────────────────────────────────────────────

export function colorPrimitivesToTailwind(
  primitives: Record<string, ColorPrimitive>,
  groupName = 'brand',
): string {
  const lines = Object.entries(primitives).map(
    ([key, token]) => `          '${key}': '${token.$value}',`,
  )

  return [
    '// tailwind.config — color tokens',
    'module.exports = {',
    '  theme: {',
    '    extend: {',
    '      colors: {',
    `        '${groupName}': {`,
    ...lines,
    '        },',
    '      },',
    '    },',
    '  },',
    '}',
  ].join('\n')
}

export function breakpointsToTailwind(tokens: Record<string, BreakpointToken>): string {
  const sorted = Object.entries(tokens).sort(([, a], [, b]) => a.$value - b.$value)
  const lines = sorted.map(
    ([key, token]) => `      '${key}': '${token.$value}${token.unit}',`,
  )

  return [
    '// tailwind.config — breakpoint tokens',
    'module.exports = {',
    '  theme: {',
    '    screens: {',
    ...lines,
    '    },',
    '  },',
    '}',
  ].join('\n')
}

export function zIndexToTailwind(tokens: Record<string, ZIndexToken>): string {
  const sorted = Object.entries(tokens).sort(([, a], [, b]) => a.$value - b.$value)
  const lines = sorted.map(
    ([key, token]) => `      '${key}': '${token.$value}', // ${token.label}`,
  )

  return [
    '// tailwind.config — z-index tokens',
    'module.exports = {',
    '  theme: {',
    '    extend: {',
    '      zIndex: {',
    ...lines,
    '      },',
    '    },',
    '  },',
    '}',
  ].join('\n')
}

// ── DTCG JSON export ───────────────────────────────────────────────────────

export function schemaToDtcg(schema: TokenSchema): string {
  const dtcg: Record<string, unknown> = {}

  // Colors
  if (Object.keys(schema.color.primitives).length > 0) {
    const color: Record<string, unknown> = {}
    for (const [key, token] of Object.entries(schema.color.primitives)) {
      color[key] = { $type: 'color', $value: token.$value }
    }
    dtcg.color = color
  }

  // Z-index
  if (Object.keys(schema.zIndex).length > 0) {
    const zIndex: Record<string, unknown> = {}
    for (const [key, token] of Object.entries(schema.zIndex)) {
      zIndex[key] = {
        $type: 'number',
        $value: token.$value,
        $description: token.label,
      }
    }
    dtcg.zIndex = zIndex
  }

  // Breakpoints
  if (Object.keys(schema.breakpoints).length > 0) {
    const breakpoints: Record<string, unknown> = {}
    for (const [key, token] of Object.entries(schema.breakpoints)) {
      breakpoints[key] = {
        $type: 'dimension',
        $value: `${token.$value}${token.unit}`,
      }
    }
    dtcg.breakpoints = breakpoints
  }

  // Focus ring
  if (schema.focusRing) {
    dtcg.focusRing = {
      color: { $type: 'color', $value: schema.focusRing.color },
      width: { $type: 'dimension', $value: `${schema.focusRing.width}px` },
      offset: { $type: 'dimension', $value: `${schema.focusRing.offset}px` },
      style: { $type: 'string', $value: schema.focusRing.style },
    }
  }

  // Dark mode
  if (Object.keys(schema.darkMode).length > 0) {
    const dark: Record<string, unknown> = {}
    for (const [key, value] of Object.entries(schema.darkMode)) {
      dark[key] = { $type: 'color', $value: value }
    }
    dtcg.darkMode = dark
  }

  return JSON.stringify(dtcg, null, 2)
}
